#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

WIREGUARD_CONF_D=/config
bf-env "WIREGUARD_CONF_D" "${WIREGUARD_CONF_D}"
bf-env "WIREGUARD_CONF" "${WIREGUARD_CONF_D}/${WIREGUARD_INTERFACE}.conf"
bf-env "WIREGUARD_SERVER_PRIVATEKEY" "${WIREGUARD_CONF_D}/privatekey"
bf-env "WIREGUARD_SERVER_PUBLICKEY" "${WIREGUARD_CONF_D}/publickey"
bf-env "WIREGUARD_PEERS_D" "${WIREGUARD_CONF_D}/peers.d"
bf-env "WIREGUARD_PEER_PRIVATEKEY_FILE" "privatekey"
bf-env "WIREGUARD_PEER_PUBLICKEY_FILE" "publickey"
bf-env "WIREGUARD_PEER_PRESHAREDKEY_FILE" "presharedkey"

bf-env "WIREGUARD_QR_ENCODING" "ansiutf8"
