#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate WireGuard configuration.
#======================================================================================================================

export PRIVATE_KEY=`cat ${WIREGUARD_PRIVATE_KEY_FILE}`
bf-esh \
    ${BF_TEMPLATES}/interface.conf.esh \
    ${WIREGUARD_CONF}
bf-done
