#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate WireGuard configuration.
#======================================================================================================================

bf-echo "Generating WireGuard server configuration."
esh \
    -o ${WIREGUARD_CONF} \
    -s /bin/bash \
    ${BF_TEMPLATES}/interface.conf.esh
